version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongogram
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: collagegram
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

#
#services:
#  mongodb:
#    image: mongodb/mongodb-community-server
#    container_name: mongodb
#    restart: unless-stopped
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin
#    volumes:
#      - mongodb_data:/data/db
#    networks:
#      - app-network
#
#  mongo-express:
#    image: mongo-express:latest
#    container_name: mongo-express
#    restart: unless-stopped
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
#      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin
#    depends_on:
#      - mongodb
#    networks:
#      - app-network
#
#volumes:
#  mongodb_data:
#
#networks:
#  app-network:
#    driver: bridge