version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongogram
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: collagegram
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-test:
    image: mongo:6.0
    container_name: mongogram
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: collagegram-test
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


